// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBeNealP8H88k8A1vQeU_VnWoBe9g0UnME',
    appId: '1:804267441478:web:46e92ac6b32bf613cb7947',
    messagingSenderId: '804267441478',
    projectId: 'track-thesis',
    authDomain: 'track-thesis.firebaseapp.com',
    storageBucket: 'track-thesis.appspot.com',
    measurementId: 'G-V61FZZNSDD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcQnBxvUQjJsPouwkxAd5QJ7u_4CfmQQc',
    appId: '1:804267441478:android:0fa69abe92f8b66ccb7947',
    messagingSenderId: '804267441478',
    projectId: 'track-thesis',
    storageBucket: 'track-thesis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqgxAU-rzVOYQFNS68Z5pWoeMdjQ73uGw',
    appId: '1:804267441478:ios:ccd3984aff3092f0cb7947',
    messagingSenderId: '804267441478',
    projectId: 'track-thesis',
    storageBucket: 'track-thesis.appspot.com',
    iosBundleId: 'com.example.thesisWebapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqgxAU-rzVOYQFNS68Z5pWoeMdjQ73uGw',
    appId: '1:804267441478:ios:4384ef31c6741c52cb7947',
    messagingSenderId: '804267441478',
    projectId: 'track-thesis',
    storageBucket: 'track-thesis.appspot.com',
    iosBundleId: 'com.example.thesisWebapp.RunnerTests',
  );
}
